### ISSUE TITLE
Support for Save Page API in OmnivoreQL?

### ISSUE THREAD

**Issue by ashutoshsaboo** [yazdipour/OmnivoreQL#11]
Hi @yazdipour , thanks for your great work on this app! Omnivore supports a `savePage` api to save a url along with a supplied html content, see here - https://docs.omnivore.app/integrations/api.html . Would it be please possible to add it to OmnivoreQL as well? I've a usecase of savings certain protected content to Omnivore which can't be achieved with `save_url` (as Omnivore won't be able to access those pages), but can only be achieved with `savePage`

Currently OmnivoreQL only supports save_url if I'm not wrong.

**Comment by ashutoshsaboo** [comment]
hey @yazdipour raised a PR here - https://github.com/yazdipour/OmnivoreQL/pull/12 . Tested locally, it works perfectly - was able to save a page to omnivore with custom HTML as well.

**Comment by ashutoshsaboo** [comment]
Can you merge the PR?

**Comment by yazdipour** [comment]
Thanks for your contribution.
Alright, I am going to merge it, since i am busy with other stuff.
But your code does not include a single test and for me as a reviewer that means it's not going to work. It would have been great to at least include one simple test scenario.
