### ISSUE TITLE
Error import OmnivoreQL

### ISSUE THREAD

**Issue by mrta** [yazdipour/OmnivoreQL#22]
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from omnivoreql import OmnivoreQL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrta/.local/lib/python3.8/site-packages/omnivoreql/__init__.py", line 1, in <module>
    from .omnivoreql import OmnivoreQL
  File "/home/mrta/.local/lib/python3.8/site-packages/omnivoreql/omnivoreql.py", line 4, in <module>
    from models import CreateLabelInput
ModuleNotFoundError: No module named 'models'

**Comment by yazdipour** [comment]
Hey @mrta Thanks for the report. 
Can you now check if things are working with version 0.3.1? 
Remove your current version (pip uninstall omnivoreql) and then install omnivoreql==0.3.1
And please let me know if its still broken!

**Comment by yazdipour** [comment]
v0.3.3 is also out with setlabel feature

**Comment by mrta** [comment]
> Hey @mrta Thanks for the report. Can you now check if things are working with version 0.3.1? Remove your current version (pip uninstall omnivoreql) and then install omnivoreql==0.3.1 And please let me know if its still broken!

Fixed.
