### ISSUE TITLE
Content is not returned using `get_articles`

### ISSUE THREAD

**Issue by MartinBernstorff** [yazdipour/OmnivoreQL#29]
AFAICT, it is because of a missing "content" on SearchSuccess:

https://github.com/yazdipour/OmnivoreQL/blob/ef00e337dd1f7169f96494dcd1afbefcb23e876c/omnivoreql/queries/Search.graphql#L15

Locally, I fixed it by adding "content", but unsure how that interacts with the method's `include_content`. 

Thanks for the work you've done here!

**Comment by yazdipour** [comment]
I hope this changes I made are exactly targeting this issue.
I appreciate if you can try these new change in v0.3.4.
