### ISSUE TITLE
Save page and delete page operations?

### ISSUE THREAD

**Issue by ashutoshsaboo** [yazdipour/OmnivoreQL#6]
Hi, thank you for the great work with this lib! By any chance does the library already support save a new page and delete existing page from omnivore operations? If not, would it be possible to please add to this lib? @yazdipour 

Many thanks for your work with this lib!

**Comment by ashutoshsaboo** [comment]
Nvm, figured it out. Saw your source here - https://github.com/yazdipour/OmnivoreQL/blob/main/omnivoreql/omnivoreql.py - to figure out the right params to get all pages in the articles list from - get_articles() , and similarly delete_article(). Was confused initially as the documentation didn't mention about the relevant params. 
Thanks for creating this lib! Closing as it's a no longer an issue

**Comment by yazdipour** [comment]
Thanks for pointing this out.
We need a better documentation.😅

**Comment by ashutoshsaboo** [comment]
Better documentation would indeed be awesome! 🚀 @yazdipour
