### ISSUE TITLE
Querying based on dates?

### ISSUE THREAD

**Issue by 0xbismarck** [yazdipour/OmnivoreQL#7]
Hello:

I've been experimenting with OmnivoreQL, and was wondering if there is a way to retrieve articles based on after the date the article was saved, or after the date a highlight was made. 

For example, I'd like to run a query for all articles I added highlights to in the last week.

**Comment by 0xbismarck** [comment]
Right after I posted this, I noticed the [date Search documentation](https://docs.omnivore.app/using/search.html#filtering-by-save-publish-dates) on Omnivore's website. I guess step one would be to try:
`get_articles(query='saved:date.._')`
to produce articles saved since a specified date.

**Comment by thiswillbeyourgithub** [comment]
Btw https://github.com/omnivore-app/omnivore/issues/3754

**Comment by jacksonh** [comment]
Hi, we are updating the docs now but it uses a `*` syntax instead of `_`

**Comment by yazdipour** [comment]
Thanks @jacksonh.
We need to improve documentation in this python client too.

**Comment by yazdipour** [comment]
Pydoc added here #13. Also included an example of using query in pydoc.
