### ISSUE TITLE
docs: meaning of argument "format"?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [yazdipour/OmnivoreQL#8]
Hi,

taking a look at `help(OmnivoreQL.get_article)` I see the argument "format: str = None" but can't find anywhere what the expected values are and what the effects are.

Thank you for clarifying this to me.

**Comment by yazdipour** [comment]
It is not clear based on their documentation what format exactly means. But bydefault html is returned and you can also change it to markdown. I have update the code and pydoc to include this information. https://github.com/yazdipour/OmnivoreQL/pull/19/commits/f88564a3bc6aca7bb0698c7bc698ea25590bdab2
