### ISSUE TITLE
Limited to 100 articles?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [yazdipour/OmnivoreQL#9]
Hi,

Am I right to believe that the API will not return more than 100 articles?

Thanks

**Comment by 0xbismarck** [comment]
I noticed that too.

**Comment by 0xbismarck** [comment]
https://github.com/0xbismarck/omnivore2trilium - my approach for getting around the 100 article limit.

**Comment by thiswillbeyourgithub** [comment]
Yeah I did pretty much the same code to fetch all articles too
